services:
  webiu-server:
    image: node:18-alpine
    container_name: webiu-server-dev
    working_dir: /usr/src/app
    ports:
      - 5050:5050
    env_file:
      - ./webiu-server/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./webiu-server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    command: [ "sh", "-c", "npm install && npm run start:dev" ]

  webiu-ui:
    image: node:18-alpine
    container_name: webiu-ui-dev
    working_dir: /usr/src/app
    volumes:
      - ./webiu-ui:/usr/src/app
      - ui_node_modules:/usr/src/app/node_modules
    ports:
      - 4200:4200
    command: [ "sh", "-c", "npm install && npx ng serve --host 0.0.0.0" ]
    depends_on:
      - webiu-server

volumes:
  server_node_modules:
  ui_node_modules:
